version: '3.5'
services:
  web-dev:
    container_name: web-dev
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - '.:/usr/src/frontend'
    ports:
      - "3000:3000"
    environment: 
      - NODE_ENV=development